version: "3.8"

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13  # Use PostgreSQL version 13
    container_name: postgres_db
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

  # FastAPI Application Service
  web:
    build: .  # Build the Dockerfile in the current directory
    container_name: fastapi_app
    command: uvicorn apps.app1.src.main:app --host 0.0.0.0 --port 8000 --reload  # Run the FastAPI app
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8000:8000"  # Expose FastAPI port
    depends_on:
      - db  # Ensure the database starts before the API
    env_file:
      - .env  # Load environment variables from .env file

# Volumes for persistent data storage
volumes:
  postgres_data:
